#
# plugins.conf -- weechat v0.4.0
#

[var]
fifo.fifo = "on"
guile.check_license = "on"
lua.check_license = "on"
perl.check_license = "on"
perl.mplex.away_msg = "Detached head"
perl.mplex.change_away_stat = "on"
perl.mplex.emit_signals = "off"
perl.mplex.exec_script_cmds = "off"
perl.mplex.interval = "60"
perl.mplex.verbose = "on"
perl.newsbar.away_only = "off"
perl.newsbar.bar_auto_hide = "on"
perl.newsbar.bar_hidden_on_start = "1"
perl.newsbar.bar_name = "newsbar"
perl.newsbar.bar_seperator = "off"
perl.newsbar.bar_title = "Highlights"
perl.newsbar.bar_visible_lines = "4"
perl.newsbar.beep_cmd = "tmux rename-window !freenode"
perl.newsbar.beep_duration = "20"
perl.newsbar.beep_freq_channel = "1000"
perl.newsbar.beep_freq_msg = "1000"
perl.newsbar.beep_freq_private = "1000"
perl.newsbar.beep_remote = "off"
perl.newsbar.beeps = "off"
perl.newsbar.colored_help = "on"
perl.newsbar.debug = "on"
perl.newsbar.format_private = "%N@%s"
perl.newsbar.format_public = "%N.%C@%s"
perl.newsbar.memo_tag_color = "yellow"
perl.newsbar.nick_flood_max_nicks = "4"
perl.newsbar.nick_flood_protection = "off"
perl.newsbar.remove_bar_on_unload = "on"
perl.newsbar.show_highlights = "on"
perl.newsbar.show_priv_msg = "on"
perl.newsbar.show_priv_server_msg = "on"
perl.newsbar.ssh_host = ""
perl.newsbar.ssh_key = ""
python.check_license = "on"
ruby.check_license = "on"
tcl.check_license = "on"

[desc]
